#!/bin/bash
# This script should be run from the recipe directory, inside a temporary Docker container
# It relies on having these commands installed:
# - tar
# - bzip2
# - wget

# install the base game
pushd /cdrom >/dev/null
ANSWERS="n
/usr/local/games/smac
/usr/local/bin
y
y
y
y
y
n
y
n
"
echo "$ANSWERS" | setup.data/bin/Linux/x86/setup
ln -s /usr/local/games/smac/smac /usr/local/bin/smac
ln -s /usr/local/games/smac/smacx /usr/local/bin/smacx
ln -s /usr/local/games/smac/smac.dynamic /usr/local/bin/smac.dynamic
ln -s /usr/local/games/smac/smacx.dynamic /usr/local/bin/smacx.dynamic
echo
popd >/dev/null

# install compat libs
tar -xjf loki_compat_libs-1.5.tar.bz2 --strip-components=1 -C /usr/local/lib
ln -s /usr/local/lib/ld-linux.so.2 /lib/ld-linux.so.2
ln -s /usr/local/lib/libc.so.6 /lib/libc.so.6

# install the patch
tar -xjf smacpatch-x86.tar.bz2 -C /tmp
pushd /tmp/smac-6.0a-x86 >/dev/null
bin/Linux/x86/loki_patch patch.dat /usr/local/games/smac
popd >/dev/null

# prepare AppImage destination dir
APPDIR=/tmp/smac.AppDir
[ -e "$APPDIR" ] && rm -r "$APPDIR"
mkdir "$APPDIR"
mkdir "$APPDIR"/lib
mkdir "$APPDIR"/usr
mkdir "$APPDIR"/usr/local
mkdir "$APPDIR"/usr/local/bin
mkdir "$APPDIR"/usr/local/games
mkdir "$APPDIR"/usr/local/lib
mkdir "$APPDIR"/usr/share
mkdir "$APPDIR"/usr/share/icons
cp /lib/ld-linux.so.2 "$APPDIR"/lib/ld-linux.so.2
cp /lib/libc.so.6 "$APPDIR"/lib/libc.so.6
cp -r /usr/local/bin/ "$APPDIR"/usr/local/
cp -r /usr/local/games/ "$APPDIR"/usr/local/
cp -r /usr/local/lib/ "$APPDIR"/usr/local/
cp /cdrom/icon.bmp "$APPDIR"/usr/share/icons/smac.bmp
cp smac.desktop "$APPDIR"

# build AppImage
# this step requires the following packages:
# - netpbm
# - wget
# - fuse
# - libglib2.0-0
# - python
# if it's running in Docker, it must have the --cap-add SYS_ADMIN --device /dev/fuse flags
bmptopnm "$APPDIR"/usr/share/icons/smac.bmp | pnmtopng > "$APPDIR"/usr/share/icons/smac.png
mkdir "$APPDIR"/usr/bin
echo "#!/bin/sh
LD_LIBRARY_PATH=local/lib local/lib/ld-linux.so.2 local/games/smac/smac.dynamic
" > "$APPDIR"/usr/bin/smac.dynamic
chmod a+x "$APPDIR"/usr/bin/smac.dynamic
echo "#!/bin/sh
LD_LIBRARY_PATH=local/lib local/lib/ld-linux.so.2 local/games/smac/smacx.dynamic
" > "$APPDIR"/usr/bin/smacx.dynamic
chmod a+x "$APPDIR"/usr/bin/smacx.dynamic
[ -e /out ] || mkdir /out
pushd /tmp >/dev/null
wget -c https://github.com/probonopd/AppImageKit/releases/download/6/AppRun_6-x86_64 -O "$APPDIR"/AppRun
chmod a+x "$APPDIR"/AppRun
wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppImageAssistant"
chmod a+x ./AppImageAssistant
./AppImageAssistant "$APPDIR" /out/smac-6.0a-i386.AppImage
popd >/dev/null
